### ISSUE TITLE
WTTR Weather Report

### ISSUE THREAD

**Issue by skyvalleyhigherpraise** [dajbelshaw/einklink#10]
**Website address**
http://wttr.in

**Description**
ASCII | Text based weather report

**Device**
Kindle Paperwhite 2020

**Comment by skyvalleyhigherpraise** [comment]
@dajbelshaw The page is too dark on Kindle Paperwhite 2020.  I'm working with the site developers to fix this.
[WTTR.IN Color Scheme · Issue #590 · chubin/wttr.in](https://github.com/chubin/wttr.in/issues/590)

**Comment by dajbelshaw** [comment]
Appreciate it - interesting conversation going on over there in that issue!

**Comment by dajbelshaw** [comment]
Any update @skyvalleyhigherpraise ?

**Comment by skyvalleyhigherpraise** [comment]
Hi Doug,

Just sent them back the bwtest3 screenshots.  I've attached them here for
your convenience.

-----
Patrick Berg

*Skyvalley Higher Praise:*

http://skyvalleyhigherpraise.com/

  <http://radio.skyvalleyhigherpraise.com/>
<https://twitter.com/skyvalleyhgrprz>
<http://church.skyvalleyhigherpraise.com>
"but if you return to Me and obey My mitzvot, and do them, then even if
your dispersed people are at the ends of the heavens, I will gather them
from there, and bring them back to the place where I have chosen for My
Name to dwell."
Nehemiah 1:9
<https://www.biblegateway.com/passage/?search=Nehemiah%201%3A4-11&version=TLV;NIV>
