### ISSUE TITLE
68k.news: Headlines From the Future Website address http://68k.news Description Basic HTML Google News for...

### ISSUE THREAD

**Issue by troutcolor** [dajbelshaw/einklink#11]
[68k.news: Headlines From the Future](http://68k.news/)

**Website address**
http://68k.news

**Description**
Basic HTML Google News for vintage computers

**Comment by dajbelshaw** [comment]
Thanks @troutcolor! This is a great find and works really well on the e-readers I've tested it on. Just added to the site :+1:
