### ISSUE TITLE
Another low impact "news" link

### ISSUE THREAD

**Issue by gitoffmyland** [dajbelshaw/einklink#13]
**Website address**
https://detoxed.news/

**Description**

Text is sourced from https://en.wikipedia.org/wiki/Portal:Current_events and made available under the Creative Commons Attribution-ShareAlike License.

This website is open source. The code is available at https://github.com/tom-james-watson/detoxed.news and is available under the MIT license.

**Device**
Kobo Aura H20

eink.link has been mentioned here:  https://old.reddit.com/r/simpleliving/comments/mne4ay/simple_online_news_and_info/

and the detoxed.news was a suggestion from a user  in that thread  (Virtual_Announcer )

**Comment by dajbelshaw** [comment]
Thanks! And apologies for the delay in replying. I've had a look at detoxed.news and it's pulling from the same source (Wikipedia current events) as Legible News, which is already listed.

Although it seems detoxed.news updates faster than Legible News, the latter is text only, and renders better on e-readers. So, to prevent duplication, I'm not going to add this one, if that's OK 😄
