### ISSUE TITLE
lightweight, monochrome friendly, reddit viewer

### ISSUE THREAD

**Issue by gitoffmyland** [dajbelshaw/einklink#14]
**Website address**
https://teddit.net

**Description**
Open source alternative Reddit front-end.  Doesn't rely on javascript.  subreddits can be accessed in the "reddit" style by appending "/r/SUBREDDIT"  to the base URL.  User profiles similarly with /u/USERNAME

example:

https://teddit.net/r/simplicity/new

This will become my access route of choice for reading reddit Posts/Comments, not only on the e-reader, but also  desktop.

**Device**
Kobo Aura H2O

**Comment by dajbelshaw** [comment]
Great, thanks @gitoffmyland - added!
