### ISSUE TITLE
frogfind

### ISSUE THREAD

**Issue by blueskiesok** [dajbelshaw/einklink#15]
**Website address**
http://frogfind.com

**Description**
Search Engine for Vintage Computers
It will strip and format sites searched to work also
Designed for old computers and devices that support HTTP and basic HTML.
This works great on eink devices

**Device**
Kindle Paperwhite 2nd gen
Likebook Mars
Kindle Oasis

**Comment by dajbelshaw** [comment]
Great stuff, thanks @blueskiesok - added! :+1:
