### ISSUE TITLE
Kinstant

### ISSUE THREAD

**Issue by blueskiesok** [dajbelshaw/einklink#16]
**Website address**
http://kinstant.com/

**Description**
Load websites faster on Kindles, phones, and dial-up PCs

**Device**
Likebook Mars
Kindle Paperwhite 2nd gen

*******
I didn't know if you had seen this website also.

**Comment by dajbelshaw** [comment]
Thanks @blueskiesok! I'm not sure which section to put this in, and don't really want to create a new section just for one link. What would you recommend? :)

**Comment by blueskiesok** [comment]
I don’t really know either. No worries. Thanks for the consideration.
The closest I could think of would be news.

**Comment by gitoffmyland** [comment]
I checked all the "google" based links out and saw no difference either on Desktop, or Kobo.

There's a note on wikipedia at: https://en.wikipedia.org/wiki/Google_Web_Light


> _In October of 2020 Google silently discontinued this service, and all Web Light links now redirect to their full version.[4]_


The links in this line:  

> check your GMail Yahoo Facebook Twitter

do appear to link to a "mobile" or other suitable presentation.

**Comment by dajbelshaw** [comment]
This website no longer exists
