### ISSUE TITLE
Games for e-readers

### ISSUE THREAD

**Issue by gitoffmyland** [dajbelshaw/einklink#17]
I used to enjoy playing chess in between "books", but that was lost in the upgrades many versions ago.  (It was "unsupported" after all).

I've discovered this site:   https://e-ink.club/

and can confirm that of the games presented, the mastermind clone works - albeit with a confusing interface.

In general though, I think a "Games" category would be good to add - whether it should be a directory pointing to other resources, or a curated, checked, listing of specific instances I'm not sure.

[I have an (old) Kobo H2O - and can only comment on suitability on that particular model.]

**Comment by dajbelshaw** [comment]
Fantastic find @gitoffmyland! I shall check and add if it's working as intended :)

**Comment by dajbelshaw** [comment]
Thanks, wow, can't believe I didn't come back to this. Added now anyway, thank you @gitoffmyland
