### ISSUE TITLE
Hard to read on Kindle PW4 (10th gen)

### ISSUE THREAD

**Issue by thumbfighter** [dajbelshaw/einklink#5]
**Describe the bug**
The contrast and small font size makes it difficult to read on Kindle Paperwhite 4(10th generation). The experimental browser doesn't seem to execute all the CSS properties.

**To Reproduce**
1. Go to 'eink.link' from the experimental browser.

**Expected behaviour**
Page elements should be bigger and width of `main` to be respected just like on the desktop browser.

**Device**
Kindle Paperwhite 4 (10th generation)

**Additional information**
A possible solution is to use webkit prefixes because the Kindle Experimental Browser is made with webkit.
The screen contrast is dependent on the e-ink devices. Dark mode might suit some devices but not all. Attached are the screenshots of the page and the actual look of the page seen with bare eyes (ok not bare eyes but close enough :))
![about_page](https://user-images.githubusercontent.com/19327775/110235356-3a971800-7ef5-11eb-9662-fc0d2f8c8c71.png)
![index_page](https://user-images.githubusercontent.com/19327775/110235358-3b2fae80-7ef5-11eb-9bfb-c632d202db6b.png)
![cameraview](https://user-images.githubusercontent.com/19327775/110235383-56022300-7ef5-11eb-9555-5911e67eb987.jpg)

**Comment by dajbelshaw** [comment]
Thanks @thumbfighter, really appreciate the time you've taken to document this. Good to know the site is loading on newer Kindles!

Could you test the new version of eink.link which now defaults to light.css (with a toggle to dark.css)? Also took a moment to hopefully improve the padding to the sides of pages 👍

**Comment by thumbfighter** [comment]
Light mode makes the readability much better.
CSS media queries don't have any effect on the Kindle browser so not sure how to get a bigger font for Kindle without making it worse for other devices. Closing the bug.
