### ISSUE TITLE
Colours 

### ISSUE THREAD

**Issue by przsak** [dajbelshaw/einklink#6]
**Describe the bug**
The page looks good on normal screen, but on eink screen it leaves bright ghost text on grey background which obstructs reading more than grey ghosts on white background, especially that fonts on Kindle browser are small and can't be changed.

**To Reproduce**
1. all pages of eink.link website

**Expected behaviour**
In my opinion colours should be inverted to make it easier to read.

**Device**
Kindle Paperwhite 7th generation

**Additional information**
[Photo 1](https://sakrajda.eu/pub/kindle1.jpg)
[Photo 2](https://sakrajda.eu/pub/kindle2.jpg)

**Comment by dajbelshaw** [comment]
Thanks @przsak! Particularly appreciate the photographs, as it seems that ghosting is worse on some devices than others. I've updated the site to default to light.css (with a toggle available to dark.css)

Does this fix the issue for you? 😃
